<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Recipe1" Id="{636c2b86-e873-4fd4-89c1-9012cc559e47}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Recipe1 : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Recipe1">
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>