<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Motor" Id="{c9894c91-c290-4e55-869d-cafa71223417}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PUBLIC Motor
VAR_INPUT
	CurrentlyMoving: BOOL;	// we need this because stepSwitches can be 1 and we should not move
	// Current position is currently stored in the Automatic GVLs.
END_VAR
VAR_OUTPUT
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Motor">
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>